openai.settings:
  type: config_object
  label: 'OpenAI API settings'
  mapping:
    api_key:
      type: string
      label: 'OpenAI API key'
    api_org:
      type: string
      label: 'OpenAI organization ID'
